import React from 'react'

import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from '@/components/ui/card'

const projects = [
    {
        title: "Real-time Fraud Detection System",
        tech: "Python, Kafka, Flink, PostgreSQL, Airflow",
        img: "images/fraud-detection.png",
        github: "https://github.com/dkkinyua/fraud-detection"
    },
    {
        title: "Reddit Sentiment Analysis",
        tech: "Python, PRAW, TextBlob, Airflow, Docker",
        img: "images/reddit-sentiment.png",
        github: "https://github.com/dkkinyua/reddit-sentiment-analysis"
    },
    {
        title: "Binance WebSocket API Project",
        tech: "Python, WebSockets, PySpark, PostgreSQL",
        img: "images/binance-websocket.png",
        github: "https://github.com/dkkinyua/binance-websocket"
    },
    {
        title: "Food Prices & Inflation Data Pipeline",
        tech: "Python, Airflow, Pandas, PostgreSQL, HDX API",
        img: "images/food-prices.png",
        github: "https://github.com/dkkinyua/food-prices-pipeline"
    },
    {
        title: "eazyetl",
        tech: "Python, pandas, requests, SQLAlchemy, psycopg2-binary, openpyxl",
        img: "https://github.com/dkkinyua/eazyetl/raw/main/docs/demo.gif",
        github: "https://github.com/dkkinyua/eazyetl",
        pypi: "https://pypi.org/project/eazyetl"
    },
    {
        title: "House Data Scraping ETL Pipeline",
        tech: "Python, BeautifulSoup, pandas, PostgreSQL, Airflow",
        img: "images/Blue Minimalist Real Estate YouTube Thumbnail (2).png",
        github: "https://github.com/dkkinyua/house-etl-pipeline"
    },
    {
        title: "Distrikt Arts",
        img: "images/Screenshot 2025-05-02 113340.png",
        live: "https://distriktarts.net"
    },
    {
        title: "Sales Rates API",
        desc: "This API calculates sales tax rates in all U.S. states. Built as a workaround to avoid third-party API fees, it uses a manually updated JSON file generated by ChatGPT prompts.",
        img: "images/Teal and Orange Gradient Abstract Tech Conference Poster (1).png",
        live: "https://tax-rates-api.onrender.com"
    }
];

function ProjectCard() {
    return (
        <div className='grid gap-6 md:grid-cols-2'>
            {projects.map((project, index) => (
                <Card key={index} className='flex flex-col overflow-hidden'>
                    <div className='aspect-video bg-muted'>
                        <img
                            src={project.img}
                            alt={`${project.title} Screenshot`}
                            loading='lazy'
                            // Some referenced screenshots aren't in public/images; hide the frame instead of showing a broken image
                            onError={(e) => { e.currentTarget.parentElement.hidden = true }}
                            className='h-full w-full object-contain'
                        />
                    </div>
                    <CardHeader className='pb-3'>
                        <CardTitle className='text-lg leading-snug'>{index + 1}. {project.title}</CardTitle>
                    </CardHeader>
                    <CardContent className='flex-1 space-y-3'>
                        {project.tech && (
                            <div className='flex flex-wrap gap-1.5'>
                                {project.tech.split(', ').map((tech) => (
                                    <Badge key={tech} variant='secondary' className='font-normal'>{tech}</Badge>
                                ))}
                            </div>
                        )}
                        {project.desc && <p className='text-sm text-muted-foreground'>{project.desc}</p>}
                    </CardContent>
                    <CardFooter className='flex-wrap justify-end gap-2'>
                        {project.github && (
                            <Button asChild size='sm'>
                                <a href={project.github} target='_blank' rel='noopener noreferrer'>
                                    <i className='fa-brands fa-github'></i> GitHub
                                </a>
                            </Button>
                        )}
                        {project.live && (
                            <Button asChild size='sm'>
                                <a href={project.live} target='_blank' rel='noopener noreferrer'>
                                    <i className='fa-solid fa-location-arrow'></i> Check it out
                                </a>
                            </Button>
                        )}
                        {project.pypi && (
                            <Button asChild size='sm'>
                                <a href={project.pypi} target='_blank' rel='noopener noreferrer'>
                                    <i className='fa-brands fa-python'></i> PyPI
                                </a>
                            </Button>
                        )}
                    </CardFooter>
                </Card>
            ))}
        </div>
    )
}

export default ProjectCard
