import React from 'react'
import { Button, Card, Container } from 'react-bootstrap'
import { Toaster } from 'react-hot-toast'

function ProjectCard() {
    const containerStyle = {
        display: 'flex',
        alignItems: 'stretch',
        width: '98%',
        marginBottom: '20px',
    };

    const cardStyle = {
        flex: 1,
        boxShadow: '0px 4px 15px rgba(0, 0, 0, 0.7)',
        overflow: 'hidden',
    };

    const textStyle = {
        fontFamily: 'PT Mono, monospace',
        fontStyle: 'normal',
    };

    // 🔥 Projects array so numbering is dynamic
    const projects = [
        {
            title: "Real-time Fraud Detection System",
            tech: "Python, Kafka, Flink, PostgreSQL, Airflow",
            img: "images/fraud-detection.png",
            github: "https://github.com/dkkinyua/fraud-detection"
        },
        {
            title: "Reddit Sentiment Analysis",
            tech: "Python, PRAW, TextBlob, Airflow, Docker",
            img: "images/reddit-sentiment.png",
            github: "https://github.com/dkkinyua/reddit-sentiment-analysis"
        },
        {
            title: "Binance WebSocket API Project",
            tech: "Python, WebSockets, PySpark, PostgreSQL",
            img: "images/binance-websocket.png",
            github: "https://github.com/dkkinyua/binance-websocket"
        },
        {
            title: "Food Prices & Inflation Data Pipeline",
            tech: "Python, Airflow, Pandas, PostgreSQL, HDX API",
            img: "images/food-prices.png",
            github: "https://github.com/dkkinyua/food-prices-pipeline"
        },
        {
            title: "eazyetl",
            tech: "Python, pandas, requests, SQLAlchemy, psycopg2-binary, openpyxl",
            img: "https://github.com/dkkinyua/eazyetl/raw/main/docs/demo.gif",
            github: "https://github.com/dkkinyua/eazyetl",
            extra: (
                <a href='https://pypi.org/project/eazyetl' target="_blank" rel="noopener noreferrer">
                    <Button variant="dark"><i className="fa-brands fa-python"></i> PyPI</Button>
                </a>
            )
        },
        {
            title: "House Data Scraping ETL Pipeline",
            tech: "Python, BeautifulSoup, pandas, PostgreSQL, Airflow",
            img: "images/Blue Minimalist Real Estate YouTube Thumbnail (2).png",
            github: "https://github.com/dkkinyua/house-etl-pipeline"
        },
        {
            title: "Distrikt Arts",
            img: "images/Screenshot 2025-05-02 113340.png",
            live: "https://distriktarts.net"
        },
        {
            title: "Sales Rates API",
            desc: "This API calculates sales tax rates in all U.S. states. Built as a workaround to avoid third-party API fees, it uses a manually updated JSON file generated by ChatGPT prompts.",
            img: "images/Teal and Orange Gradient Abstract Tech Conference Poster (1).png",
            live: "https://tax-rates-api.onrender.com"
        }
    ];

    return (
        <Container fluid>
            <div>
                <Toaster />
            </div>
            <div>
                {projects.map((project, index) => (
                    <div style={containerStyle} key={index}>
                        <Card style={cardStyle}>
                            <Card.Title style={textStyle} className="p-3">
                                <h2>{index + 1}. {project.title}</h2>
                            </Card.Title>
                            <Card.Body className="d-flex flex-column" style={textStyle}>
                                {project.tech && <p><strong>Tech Stack:</strong> {project.tech}</p>}
                                {project.desc && <p>{project.desc}</p>}
                                <img
                                    src={project.img}
                                    alt={`${project.title} Screenshot`}
                                    style={{ width: '100%', borderRadius: '8px', marginBottom: '15px', height:'300px' }}
                                />
                                <div className="d-flex justify-content-end gap-3">
                                    {project.github && (
                                        <a href={project.github} target="_blank" rel="noopener noreferrer">
                                            <Button variant="dark"><i className="fa-brands fa-github"></i> GitHub</Button>
                                        </a>
                                    )}
                                    {project.live && (
                                        <a href={project.live} target="_blank" rel="noopener noreferrer">
                                            <Button variant="dark"><i className="fa-solid fa-location-arrow"></i> Check it out</Button>
                                        </a>
                                    )}
                                    {project.extra && project.extra}
                                </div>
                            </Card.Body>
                        </Card>
                    </div>
                ))}
            </div>
        </Container>
    )
}

export default ProjectCard
